<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';
import { DownloadOutlined, EditOutlined, ImportOutlined, MessageOutlined, PlusOutlined, SearchOutlined, EyeOutlined, DeleteOutlined, CameraOutlined, EnvironmentOutlined } from '@ant-design/icons-vue';
import { message } from 'ant-design-vue';
import TableColumnSettings from './TableColumnSettings.vue';
import ImportReviewModal, { type ImportColumn } from './ImportReviewModal.vue';

type WaybillSource = 'upstream' | 'manual' | 'wechat';
interface WaybillRecord { id:string; projectId:string; source:WaybillSource; sourceName:string; waybillNo:string; thirdOrderNo:string; route:string; loadingAddress:string; unloadingAddress:string; loadingTime:string; unloadingTime:string; creator:string; createdAt:string; remark:string; vehiclePlate:string; trailerPlate:string; primaryDriver:string; primaryDriverPhone:string; secondaryDriver:string; goodsName:string; goodsType:string; weight:number; volume:number; quantity:number; upstreamFreight:number; downstreamFreight:number; mileage:number; status:string; robotReply?:string; }
const props = defineProps<{ projectId: string; projectName: string }>();

const sourceLabels: Record<WaybillSource,string> = { upstream:'自动同步', manual:'人工录入', wechat:'企微群抓取' };
const sourceColors: Record<WaybillSource,string> = { upstream:'blue', manual:'default', wechat:'green' };
const statuses = ['待装货','运输中','已送达','已取消'];
const routes = ['砚山储配站-广西德保电厂','华银厂区-田东华银料场','威信集运站-昭通电厂'];
const rows = ref<WaybillRecord[]>(Array.from({ length: 24 }, (_, index) => {
  const source: WaybillSource = index % 3 === 0 ? 'upstream' : index % 3 === 1 ? 'manual' : 'wechat';
  const route = routes[index % routes.length]; const [loadingAddress, unloadingAddress] = route.split('-');
  return { id:`WB-${index+1}`, projectId:`p${index%7+1}`, source, sourceName:source === 'upstream' ? (index % 2 ? '京东' : '德邦') : sourceLabels[source], waybillNo:`YD202608${String(index+1).padStart(5,'0')}`, thirdOrderNo:source === 'upstream' ? `THIRD-${868000+index}` : `SO-${2608000+index}`, route, loadingAddress, unloadingAddress, loadingTime:`2026-08-${String(18-index%8).padStart(2,'0')} 08:${String(index*7%60).padStart(2,'0')}`, unloadingTime:index%4===0?'':`2026-08-${String(18-index%8).padStart(2,'0')} 18:${String(index*9%60).padStart(2,'0')}`, creator:source==='wechat'?'企微数据机器人':source==='upstream'?'系统同步':'本地联调真实姓名', createdAt:`2026-08-${String(18-index%8).padStart(2,'0')} 07:30`, remark:source==='wechat'?'群消息自动建单':'', vehiclePlate:`云A${String(6238+index).padStart(5,'0')}`, trailerPlate:`云A挂${String(318+index).padStart(4,'0')}`, primaryDriver:['罗明','邓华','张勇'][index%3], primaryDriverPhone:`1380000${String(1000+index).slice(-4)}`, secondaryDriver:index%2?'刘师傅':'', goodsName:['煤炭','氧化铝','水泥熟料'][index%3], goodsType:['散装','袋装','散装'][index%3], weight:Number((38.5+index*.37).toFixed(2)), volume:index%3===1?32:0, quantity:index%3===1?420:1, upstreamFreight:2800+index*35, downstreamFreight:2350+index*30, mileage:180+index*9, status:statuses[index%statuses.length], robotReply:source==='wechat'?'已收到，运单已创建并同步至系统。':undefined };
}));
const keyword=ref(''); const sourceFilter=ref<'全部'|WaybillSource>('全部'); const statusFilter=ref('全部'); const addVisible=ref(false); const editingId=ref('');
const form=reactive<Record<string,any>>({});
const quickText=ref('');
const historyWaybills=computed(()=>rows.value.filter(row=>row.projectId===props.projectId).slice(0,6));
function fillFromHistory(record:WaybillRecord){Object.assign(form,{route:record.route,loadingAddress:record.loadingAddress,unloadingAddress:record.unloadingAddress,vehiclePlate:record.vehiclePlate,trailerPlate:record.trailerPlate,primaryDriver:record.primaryDriver,primaryDriverPhone:record.primaryDriverPhone,secondaryDriver:record.secondaryDriver,goodsName:record.goodsName,goodsType:record.goodsType,weight:record.weight,volume:record.volume,quantity:record.quantity,upstreamFreight:record.upstreamFreight,downstreamFreight:record.downstreamFreight,mileage:record.mileage});message.success('已回填历史运单信息');}
function recognizeQuickText(){const text=quickText.value.trim();if(!text){message.warning('请先粘贴运单文字');return;}const phone=text.match(/1\d{10}/)?.[0];const plate=text.match(/[\u4e00-\u9fa5][A-Z][A-Z0-9]{5,6}/)?.[0];const time=text.match(/20\d{2}[-/]\d{1,2}[-/]\d{1,2}(?:\s+\d{1,2}:\d{2})?/)?.[0];const route=text.match(/([^\n，,]+?)[-→至]([^\n，,]+)/);if(phone)form.primaryDriverPhone=phone;if(plate)form.vehiclePlate=plate;if(time)form.loadingTime=time.replace(/\//g,'-');if(route){form.loadingAddress=route[1].trim();form.unloadingAddress=route[2].trim();form.route=`${form.loadingAddress}-${form.unloadingAddress}`;}const driver=text.match(/(?:司机|主驾)[：:\s]*([\u4e00-\u9fa5]{2,4})/)?.[1];if(driver)form.primaryDriver=driver;message.success('已识别并回填，请核对必填字段');}
const filtered=computed(()=>rows.value.filter(row=>row.projectId===props.projectId&&(sourceFilter.value==='全部'||row.source===sourceFilter.value)&&(statusFilter.value==='全部'||row.status===statusFilter.value)&&(!keyword.value.trim()||Object.values(row).some(value=>String(value??'').includes(keyword.value.trim())))));
const summary=computed(()=>({ total:filtered.value.length, upstream:filtered.value.filter(r=>r.source==='upstream').length, manual:filtered.value.filter(r=>r.source==='manual').length, wechat:filtered.value.filter(r=>r.source==='wechat').length, transit:filtered.value.filter(r=>r.status==='运输中').length }));
const baseColumns=[{title:'来源',dataIndex:'source',width:120},{title:'运单号',dataIndex:'waybillNo',width:150},{title:'三方订单号',dataIndex:'thirdOrderNo',width:150},{title:'线路',dataIndex:'route',width:210},{title:'装货地址 *',dataIndex:'loadingAddress',width:150},{title:'卸货地址 *',dataIndex:'unloadingAddress',width:150},{title:'装货时间 *',dataIndex:'loadingTime',width:150},{title:'卸货时间',dataIndex:'unloadingTime',width:150},{title:'建单人',dataIndex:'creator',width:130},{title:'建单时间',dataIndex:'createdAt',width:150},{title:'备注',dataIndex:'remark',width:170},{title:'车牌号 *',dataIndex:'vehiclePlate',width:110},{title:'挂车牌',dataIndex:'trailerPlate',width:110},{title:'主驾姓名 *',dataIndex:'primaryDriver',width:100},{title:'主驾手机号 *',dataIndex:'primaryDriverPhone',width:125},{title:'副驾',dataIndex:'secondaryDriver',width:90},{title:'货物名称',dataIndex:'goodsName',width:110},{title:'货物类型',dataIndex:'goodsType',width:100},{title:'货物重量（吨）',dataIndex:'weight',width:125},{title:'货物体积（方）',dataIndex:'volume',width:125},{title:'货物件数',dataIndex:'quantity',width:100},{title:'上游运费',dataIndex:'upstreamFreight',width:110},{title:'下游运费',dataIndex:'downstreamFreight',width:110},{title:'里程',dataIndex:'mileage',width:90},{title:'运输状态',dataIndex:'status',width:100},{title:'操作',dataIndex:'action',fixed:'right',width:220,className:'waybill-action-column'}];
const defaultKeys=baseColumns.filter(c=>c.dataIndex!=='action').map(c=>c.dataIndex); const fieldKeys=ref<string[]>(JSON.parse(localStorage.getItem('waybill-table-columns')||'null')||defaultKeys); watch(fieldKeys,v=>localStorage.setItem('waybill-table-columns',JSON.stringify(v)),{deep:true});
const columns=computed(()=>[...fieldKeys.value.map(key=>baseColumns.find(c=>c.dataIndex===key)).filter(Boolean),baseColumns.find(c=>c.dataIndex==='action')]);
function openAdd(record?:WaybillRecord){ editingId.value=record?.id||''; Object.assign(form,record||{projectId:props.projectId,source:'manual',waybillNo:`YD${Date.now()}`,thirdOrderNo:'',route:'',loadingAddress:'',unloadingAddress:'',loadingTime:'',unloadingTime:'',creator:'本地联调真实姓名',createdAt:'2026-08-19 10:00',remark:'',vehiclePlate:'',trailerPlate:'',primaryDriver:'',primaryDriverPhone:'',secondaryDriver:'',goodsName:'',goodsType:'',weight:0,volume:0,quantity:1,upstreamFreight:0,downstreamFreight:0,mileage:0,status:'待装货'}); addVisible.value=true; }
function save(){ const required=[form.vehiclePlate,form.loadingTime,form.primaryDriver,form.primaryDriverPhone,form.loadingAddress,form.unloadingAddress]; if(required.some(value=>!String(value||'').trim())){message.warning('请填写车牌号、装货时间、主驾姓名和手机号、装卸货地址');return;} if(!/^1\d{10}$/.test(String(form.primaryDriverPhone))){message.warning('请输入正确的 11 位主驾手机号');return;} if(editingId.value){rows.value=rows.value.map(r=>r.id===editingId.value?{...r,...form} as WaybillRecord:r);}else rows.value.unshift({...form,id:`WB-${Date.now()}`,source:'manual',sourceName:'人工录入'} as WaybillRecord); addVisible.value=false; message.success(editingId.value?'运单已保存':'运单已创建'); }
const importVisible=ref(false); const importInput=ref<HTMLInputElement|null>(null); const importFileName=ref('运单批量导入.xlsx');
const importColumns: ImportColumn[]=[{key:'vehiclePlate',label:'车牌号',sourceNames:['车牌号'],required:true},{key:'loadingTime',label:'装货时间',sourceNames:['装货时间'],required:true},{key:'primaryDriver',label:'主驾姓名',sourceNames:['司机姓名'],required:true},{key:'primaryDriverPhone',label:'主驾手机号',sourceNames:['司机手机号'],required:true},{key:'loadingAddress',label:'装货地址',sourceNames:['装货地址'],required:true},{key:'unloadingAddress',label:'卸货地址',sourceNames:['卸货地址'],required:true},{key:'waybillNo',label:'运单号',sourceNames:['运单号']},{key:'goodsName',label:'货物名称',sourceNames:['货物名称']}];
const importRowsSample=[{vehiclePlate:'云A62380',loadingTime:'2026-08-20 08:00',primaryDriver:'罗明',primaryDriverPhone:'13800001000',loadingAddress:'砚山储配站',unloadingAddress:'广西德保电厂',waybillNo:'YD202608001',goodsName:'煤炭'},{vehiclePlate:'',loadingTime:'2026-08-20 09:00',primaryDriver:'邓华',primaryDriverPhone:'13800001001',loadingAddress:'华银厂区',unloadingAddress:'田东华银料场',waybillNo:'YD202608002',goodsName:'氧化铝'}];
function importRows(){ const input=document.createElement('input'); input.type='file'; input.accept='.xlsx,.xls,.csv'; input.onchange=onImportFile; input.click(); }
function onImportFile(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file)return;if(!/\.(xlsx|xls|csv)$/i.test(file.name)){message.error('请选择 XLSX、XLS 或 CSV 文件');return;}if(file.size>10*1024*1024){message.error('文件不能超过 10 MB');return;}importFileName.value=file.name;importVisible.value=true;}
function confirmImport(imported:Array<Record<string,string|number|null>>){const valid=imported.filter(row=>/^1\d{10}$/.test(String(row.primaryDriverPhone||'')));rows.value.unshift(...valid.map(row=>({...row,id:`WB-${Date.now()}-${Math.random()}`,projectId:props.projectId,source:'manual',sourceName:'人工录入',thirdOrderNo:'',route:'',unloadingTime:'',creator:'批量导入',createdAt:new Date().toLocaleString('zh-CN'),remark:'',trailerPlate:'',secondaryDriver:'',goodsType:'',weight:0,volume:0,quantity:1,upstreamFreight:0,downstreamFreight:0,mileage:0,status:'待装货'} as WaybillRecord)));message.success(`已导入 ${valid.length} 条运单`);}
function sourceColor(source: WaybillSource){ return sourceColors[source]; }
function sourceText(record: WaybillRecord){ return record.source==='upstream'?`${sourceLabels[record.source]} · ${record.sourceName}`:sourceLabels[record.source]; }
function recordValue(record: WaybillRecord,key:string){ return (record as unknown as Record<string,unknown>)[key]; }
const detailVisible=ref(false); const detailTab=ref('basic'); const selectedRecord=ref<WaybillRecord|null>(null); const reportPhoto=ref('/Users/xrh/Desktop/微信图片_20260821102014_16_1.jpg');
function openDetail(record:WaybillRecord){selectedRecord.value=record;detailTab.value='basic';detailVisible.value=true;}
function removeRecord(record:WaybillRecord){if(!window.confirm(`确定删除运单 ${record.waybillNo} 吗？`))return;rows.value=rows.value.filter(item=>item.id!==record.id);message.success('运单已删除');}
function attachReportPhoto(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file){reportPhoto.value=URL.createObjectURL(file);message.success('报备照片已关联');}}
</script>

<template><section class="content list-screen waybill-page"><div class="page-toolbar"><div><h2>运单列表</h2><span>汇总上游系统、人工录入和企微群自动建单数据</span></div><div class="toolbar-actions"><input ref="importInput" class="hidden-file-input" type="file" accept=".xlsx,.xls,.csv" @change="onImportFile"/><a-button @click="importRows"><ImportOutlined />批量导入</a-button><a-button type="primary" @click="openAdd()"><PlusOutlined />手动录入</a-button><TableColumnSettings v-model="fieldKeys" :columns="baseColumns"/><a-button><DownloadOutlined />导出</a-button></div></div>
<div class="metric-grid five"><div class="metric-card"><span>全部运单</span><strong>{{summary.total}}</strong></div><div class="metric-card"><span>自动同步</span><strong>{{summary.upstream}}</strong></div><div class="metric-card"><span>人工录入</span><strong>{{summary.manual}}</strong></div><div class="metric-card"><span>企微群抓取</span><strong>{{summary.wechat}}</strong></div><div class="metric-card orange"><span>运输中</span><strong>{{summary.transit}}</strong></div></div>
<div class="filter-bar"><a-input v-model:value="keyword" allow-clear placeholder="搜索运单号、订单号、线路、车牌、司机、货物"><template #prefix><SearchOutlined/></template></a-input><a-select v-model:value="sourceFilter"><a-select-option value="全部">全部来源</a-select-option><a-select-option value="upstream">自动同步（京东/德邦）</a-select-option><a-select-option value="manual">人工录入</a-select-option><a-select-option value="wechat">企微群抓取</a-select-option></a-select><a-select v-model:value="statusFilter"><a-select-option value="全部">全部状态</a-select-option><a-select-option v-for="item in statuses" :key="item" :value="item">{{item}}</a-select-option></a-select></div>
<a-table :columns="columns" :data-source="filtered" row-key="id" size="small" :pagination="{pageSize:10}" :scroll="{x:3100}" class="dense-table"><template #bodyCell="{column,record}"><template v-if="column.dataIndex==='source'"><a-tag :color="sourceColor(record.source)">{{sourceText(record)}}</a-tag><a-tooltip v-if="record.robotReply" :title="record.robotReply"><MessageOutlined class="robot-reply"/></a-tooltip></template><template v-else-if="column.dataIndex==='status'"><a-tag :color="record.status==='已送达'?'green':record.status==='运输中'?'blue':record.status==='已取消'?'red':'orange'">{{record.status}}</a-tag></template><template v-else-if="['upstreamFreight','downstreamFreight'].includes(column.dataIndex)">¥{{Number(recordValue(record,column.dataIndex)).toLocaleString()}}</template><template v-else-if="column.dataIndex==='action'"><div class="waybill-actions"><a-tooltip title="查看详情"><a-button type="link" size="small" aria-label="查看详情" @click="openDetail(record)"><EyeOutlined/><span>查看</span></a-button></a-tooltip><a-tooltip title="编辑运单"><a-button type="link" size="small" aria-label="编辑运单" @click="openAdd(record)"><EditOutlined/><span>编辑</span></a-button></a-tooltip><a-tooltip title="删除运单"><a-button type="link" danger size="small" aria-label="删除运单" @click="removeRecord(record)"><DeleteOutlined/><span>删除</span></a-button></a-tooltip></div></template></template><template #emptyText><a-empty description="暂无运单数据"/></template></a-table>
<a-modal v-model:open="addVisible" :title="editingId?'编辑运单':'手动录入运单'" width="1120px" ok-text="保存" @ok="save"><div class="waybill-entry-layout"><aside class="waybill-quick"><h4>快捷操作</h4><span>粘贴文字识别快速下单</span><a-textarea v-model:value="quickText" :rows="7" placeholder="粘贴司机发送的运单信息"/><a-button type="primary" block @click="recognizeQuickText">识别并回填</a-button><h4>历史运单</h4><button v-for="item in historyWaybills" :key="item.id" type="button" class="history-waybill" @click="fillFromHistory(item)"><b>{{item.loadingAddress}} → {{item.unloadingAddress}}</b><span>{{item.vehiclePlate}} · {{item.primaryDriver}} · {{item.goodsName}}</span></button></aside><div class="waybill-form"><label v-for="column in baseColumns.filter(c=>!['source','action'].includes(c.dataIndex))" :key="column.dataIndex"><span>{{column.title}}</span><a-select v-if="column.dataIndex==='status'" v-model:value="form.status"><a-select-option v-for="item in statuses" :key="item" :value="item">{{item}}</a-select-option></a-select><a-input-number v-else-if="['weight','volume','quantity','upstreamFreight','downstreamFreight','mileage'].includes(column.dataIndex)" v-model:value="form[column.dataIndex]" :min="0" style="width:100%"/><a-input v-else v-model:value="form[column.dataIndex]"/></label></div></div></a-modal>
<ImportReviewModal v-model:open="importVisible" title="批量导入运单 · 字段映射与校验" :file-name="importFileName" :columns="importColumns" :sample-rows="importRowsSample" @confirm="confirmImport"/>
<a-modal v-model:open="detailVisible" title="运单详情" width="1100px" :footer="null" class="waybill-detail-modal"><a-tabs v-model:activeKey="detailTab"><a-tab-pane key="basic" tab="基础信息"><template v-if="selectedRecord"><div class="detail-summary"><span>运单号：<b>{{selectedRecord.waybillNo}}</b></span><span>客户名称：-</span><span>项目：{{projectName}}</span><span>上游运费：¥{{selectedRecord.upstreamFreight}}</span><span>下游运费：¥{{selectedRecord.downstreamFreight}}</span><span>备注：{{selectedRecord.remark||'-'}}</span></div><div class="route-cards"><div><EnvironmentOutlined/><b>装货点</b><h3>{{selectedRecord.loadingAddress}}</h3><p>{{selectedRecord.loadingTime}}</p></div><strong class="route-arrow">→</strong><div><EnvironmentOutlined/><b>卸货点</b><h3>{{selectedRecord.unloadingAddress}}</h3><p>{{selectedRecord.unloadingTime||'-'}}</p></div></div><h4>承运信息</h4><a-descriptions bordered size="small" :column="4"><a-descriptions-item label="车牌号">{{selectedRecord.vehiclePlate}}</a-descriptions-item><a-descriptions-item label="主驾">{{selectedRecord.primaryDriver}} {{selectedRecord.primaryDriverPhone}}</a-descriptions-item><a-descriptions-item label="副驾">{{selectedRecord.secondaryDriver||'-'}}</a-descriptions-item><a-descriptions-item label="挂车牌">{{selectedRecord.trailerPlate||'-'}}</a-descriptions-item></a-descriptions><h4>货物信息</h4><a-descriptions bordered size="small" :column="4"><a-descriptions-item label="货物名称">{{selectedRecord.goodsName||'-'}}</a-descriptions-item><a-descriptions-item label="货物类型">{{selectedRecord.goodsType||'-'}}</a-descriptions-item><a-descriptions-item label="重量（吨）">{{selectedRecord.weight||'-'}}</a-descriptions-item><a-descriptions-item label="件数">{{selectedRecord.quantity||'-'}}</a-descriptions-item></a-descriptions></template></a-tab-pane><a-tab-pane key="trip" tab="行程展示"><div class="trip-empty">装货 → 运输中 → 卸货<br/><small>行程轨迹将在车辆定位数据接入后展示</small></div></a-tab-pane><a-tab-pane key="report" tab="报备明细"><div class="report-panel"><a-descriptions bordered size="small" :column="3"><a-descriptions-item label="车牌号">{{selectedRecord?.vehiclePlate}}</a-descriptions-item><a-descriptions-item label="司机">{{selectedRecord?.primaryDriver}} {{selectedRecord?.primaryDriverPhone}}</a-descriptions-item><a-descriptions-item label="运输状态">{{selectedRecord?.status}}</a-descriptions-item><a-descriptions-item label="装货时间">{{selectedRecord?.loadingTime}}</a-descriptions-item><a-descriptions-item label="装货地址">{{selectedRecord?.loadingAddress}}</a-descriptions-item><a-descriptions-item label="卸货地址">{{selectedRecord?.unloadingAddress}}</a-descriptions-item></a-descriptions><div class="report-photo"><input id="report-photo" type="file" accept="image/*" @change="attachReportPhoto"/><label for="report-photo"><CameraOutlined/> 上传水印相机照片</label><img v-if="reportPhoto" :src="reportPhoto" alt="报备照片"/></div></div></a-tab-pane></a-tabs></a-modal></section></template>

<style scoped>.page-toolbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.page-toolbar h2{margin:0;font-size:18px}.page-toolbar>div>span{color:#64748b;font-size:12px}.toolbar-actions{display:flex;gap:8px}.hidden-file-input{display:none}.robot-reply{margin-left:5px;color:#16a34a}.waybill-actions{display:flex;align-items:center;justify-content:flex-start;gap:2px;white-space:nowrap}.waybill-actions :deep(.ant-btn){padding-inline:5px}.waybill-form{display:grid;grid-template-columns:1fr 1fr;gap:12px 16px;max-height:62vh;overflow:auto}.waybill-form label{display:grid;grid-template-columns:105px 1fr;align-items:center;gap:8px}.waybill-form label span{color:#475569;font-size:12px}.detail-summary{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;background:#fafafa;padding:14px;font-size:12px}.route-cards{display:flex;align-items:center;gap:18px;padding:18px 10px}.route-cards>div{flex:1;border-bottom:3px solid #55c8a6;padding:12px;background:#fff;border:1px solid #eee}.route-cards>div:last-child{border-bottom-color:#ff4d4f}.route-cards h3{margin:10px 0 4px}.route-cards p{color:#64748b}.route-arrow{font-size:32px}.waybill-detail-modal h4{border-left:3px solid #fa8c16;padding-left:8px}.trip-empty{text-align:center;padding:80px;color:#64748b}.report-panel{padding:8px}.report-photo{margin-top:18px;border:1px dashed #cbd5e1;padding:24px;text-align:center}.report-photo label{display:inline-flex;gap:8px;align-items:center;color:#1677ff;cursor:pointer}.report-photo input{display:none}.report-photo img{display:block;max-width:240px;max-height:180px;margin:16px auto 0}@media(max-width:1000px){.toolbar-actions{flex-wrap:wrap}.waybill-form{grid-template-columns:1fr}.detail-summary{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.waybill-actions span{display:none}.waybill-action-column{width:132px!important}.waybill-actions :deep(.ant-btn){padding-inline:7px}.page-toolbar{align-items:flex-start;gap:10px;flex-wrap:wrap}.filter-bar{flex-wrap:wrap}}</style>
<style scoped>
.detail-summary span:nth-child(2), .detail-summary span:nth-child(3) { display:none; }
.waybill-detail-modal :global(.ant-tabs-nav-list .ant-tabs-tab:nth-child(2)) { display:none !important; }
.waybill-detail-modal :global(.ant-tabs-content-holder .ant-tabs-tabpane:nth-child(2)) { display:none !important; }
.waybill-detail-modal :global(.ant-tabs-nav-list) { gap:0; }
.report-photo { position:relative; text-align:left; padding:20px 24px 20px 52px; border:0; border-left:2px solid #dbeafe; margin-left:18px; }
.report-photo:before { content:'已到卸货地'; display:block; color:#1f2937; font-size:16px; font-weight:600; margin-bottom:5px; }
.report-photo:after { content:'司机：' attr(data-driver); display:block; color:#64748b; font-size:12px; margin-bottom:12px; }
.report-photo:before { content:'已到卸货地'; }
.report-photo img:not([src=""]) { display:block; }
.report-photo:empty:after { content:'水印相机照片已自动关联到该行程'; color:#94a3b8; }
.report-photo label { display:none; }
.report-photo input { display:none; }
 .waybill-entry-layout{display:grid;grid-template-columns:250px minmax(0,1fr);gap:18px}.waybill-quick{max-height:62vh;overflow:auto;padding-right:16px;border-right:1px solid #e5e7eb}.waybill-quick h4{margin:2px 0 10px;padding-left:8px;border-left:3px solid #fa8c16}.waybill-quick h4:nth-of-type(2){margin-top:20px}.waybill-quick>span{display:block;margin-bottom:8px;color:#64748b;font-size:12px}.waybill-quick>.ant-btn{margin-top:10px}.history-waybill{display:block;width:100%;padding:8px 4px;border:0;border-bottom:1px solid #f1f5f9;background:transparent;text-align:left;cursor:pointer}.history-waybill:hover{background:#fff7ed}.history-waybill b,.history-waybill span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.history-waybill b{color:#334155;font-size:12px}.history-waybill span{margin-top:3px;color:#94a3b8;font-size:11px}@media(max-width:900px){.waybill-entry-layout{grid-template-columns:1fr}.waybill-quick{max-height:none;border-right:0;border-bottom:1px solid #e5e7eb;padding:0 0 14px}}
</style>
<style scoped>
.waybill-entry-layout { grid-template-columns: minmax(0,1fr) 250px; }
.waybill-quick { grid-column: 2; grid-row: 1; padding-left: 16px; padding-right: 0; border-left: 1px solid #e5e7eb; border-right: 0; }
.waybill-entry-layout > .waybill-form { grid-column: 1; grid-row: 1; }
</style>
