import type { AgentMessage, Expense, FieldBox, Project, Vehicle, WeighBill } from './types';

export const weighImage = '/demo-assets/weighbridge.jpg';
export const expenseImages = [
  '/demo-assets/expense-1.png',
  '/demo-assets/expense-2.jpg',
  '/demo-assets/expense-3.jpg',
  '/demo-assets/expense-4.jpg',
  '/demo-assets/expense-5.jpg',
  '/demo-assets/expense-6.jpg',
  '/demo-assets/expense-7.jpg'
];

export const weighFieldBoxes: FieldBox[] = [
  { key: 'receiver', label: '收货单位', x: 13, y: 21, w: 24, h: 4.8 },
  { key: 'shipper', label: '发货单位', x: 45, y: 21, w: 34, h: 4.8 },
  { key: 'goods', label: '货物名称', x: 18, y: 38, w: 13, h: 5 },
  { key: 'mineType', label: '矿别', x: 34, y: 38, w: 10, h: 5 },
  { key: 'gross', label: '毛重', x: 43, y: 41, w: 8, h: 5 },
  { key: 'tare', label: '皮重', x: 62, y: 41, w: 7, h: 5 },
  { key: 'net', label: '净重', x: 76, y: 41, w: 8, h: 5 },
  { key: 'carrier', label: '承运单位', x: 20, y: 48, w: 27, h: 6 },
  { key: 'vehiclePlate', label: '车号', x: 55, y: 49, w: 13, h: 5 },
  { key: 'driver', label: '驾驶员', x: 75, y: 48, w: 11, h: 7 },
  { key: 'remark', label: '备注', x: 19, y: 58, w: 23, h: 5 },
  { key: 'dateTime', label: '磅单时间', x: 48, y: 69, w: 20, h: 5 }
];

export const expenseFieldBoxes: FieldBox[] = [
  { key: 'driver', label: '司机', x: 30, y: 24, w: 18, h: 4.5 },
  { key: 'vehiclePlate', label: '车号', x: 31, y: 20, w: 22, h: 4.5 },
  { key: 'type', label: '报销类型', x: 24, y: 40, w: 18, h: 4.5 },
  { key: 'item', label: '报销事项', x: 24, y: 37, w: 42, h: 14 },
  { key: 'amount', label: '金额', x: 52, y: 50, w: 16, h: 5 },
  { key: 'occurredDate', label: '发生日期', x: 23, y: 15, w: 28, h: 4.5 },
  { key: 'payee', label: '付款对象', x: 20, y: 62, w: 38, h: 5 }
];

export const projects: Project[] = [
  {
    id: 'p1',
    name: '云南煤炭储配运输项目',
    route: '客户：云南省煤炭交易（储配）中心｜线路：砚山→德保电厂、砚山→靖西天桂、广西华银→砚山',
    vehicles: 10,
    pending: 9,
    profit: 48260,
    status: '关注'
  },
  {
    id: 'p2',
    name: '曲靖城建砂石配送项目',
    route: '客户：曲靖城建物资｜线路：富源采石场→曲靖园区、曲靖料场→宣威搅拌站、宣威北站→富源中转场',
    vehicles: 10,
    pending: 3,
    profit: 23840,
    status: '正常'
  },
  {
    id: 'p3',
    name: '广西华银氧化铝运输项目',
    route: '客户：广西华银铝业｜线路：华银→田东、田东→靖西、砚山→田东',
    vehicles: 10,
    pending: 5,
    profit: -1860,
    status: '异常'
  },
  {
    id: 'p4',
    name: '昭通电煤干线运输项目',
    route: '客户：昭通能源集团｜线路：威信→昭通电厂、镇雄→水富码头、彝良→盐津储煤库',
    vehicles: 6,
    pending: 4,
    profit: 31680,
    status: '正常'
  },
  {
    id: 'p5',
    name: '黔西南水泥熟料配送项目',
    route: '客户：黔西南海螺水泥｜线路：兴义熟料库→晴隆搅拌站、安龙粉磨站→册亨项目部',
    vehicles: 6,
    pending: 6,
    profit: 28420,
    status: '关注'
  },
  {
    id: 'p6',
    name: '滇中新能源矿粉转运项目',
    route: '客户：滇中新材料科技｜线路：安宁中转仓→滇中新区工厂、嵩明矿粉库→昆明经开仓',
    vehicles: 6,
    pending: 2,
    profit: 22790,
    status: '正常'
  },
  {
    id: 'p7',
    name: '百色铝土矿短倒项目',
    route: '客户：百色矿业集团｜线路：平果矿区→百色氧化铝厂、田阳堆场→田东码头',
    vehicles: 6,
    pending: 5,
    profit: 17340,
    status: '关注'
  }
];

export const vehicles: Vehicle[] = [
  { id: 'v1', plate: '赣J03528D', trailer: '赣J528挂', driver: '罗明', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v2', plate: '赣J01379D', trailer: '赣J379挂', driver: '邓华', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v3', plate: '赣J00236D', trailer: '赣J236挂', driver: '刘启', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v4', plate: '赣J05550D', trailer: '赣J550挂', driver: '张勇', owner: '云南云志合通', projectId: 'p1', status: '待检修', model: '新能源重卡' },
  { id: 'v5', plate: '沪A20170A', trailer: '沪A170挂', driver: '王成', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '燃油牵引车' },
  { id: 'v6', plate: '沪A16565A', trailer: '沪A565挂', driver: '陈力', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '燃油牵引车' },
  { id: 'v7', plate: '粤B98790D', trailer: '桂L5346挂', driver: '何明军', owner: '华银物流队', projectId: 'p3', status: '运营中', model: '新能源重卡' },
  { id: 'v8', plate: '沪A15230A', trailer: '沪A230挂', driver: '李进', owner: '华银物流队', projectId: 'p3', status: '停运', model: '燃油牵引车' },
  { id: 'v9', plate: '赣J00607D', trailer: '赣J607挂', driver: '程大昌', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v10', plate: '赣J02906D', trailer: '赣J906挂', driver: '胡俊', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v11', plate: '沪A12097A', trailer: '沪A097挂', driver: '周兵', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '燃油牵引车' },
  { id: 'v12', plate: '沪A04114D', trailer: '沪A114挂', driver: '李玉红', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '燃油牵引车' },
  { id: 'v13', plate: '沪A18882A', trailer: '沪A882挂', driver: '赵启明', owner: '曲靖捷运', projectId: 'p2', status: '待检修', model: '燃油牵引车' },
  { id: 'v14', plate: '沪A17621A', trailer: '沪A621挂', driver: '马德林', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '新能源重卡' },
  { id: 'v15', plate: '粤B32450D', trailer: '桂L2450挂', driver: '潘加松', owner: '华银物流队', projectId: 'p3', status: '运营中', model: '新能源重卡' },
  { id: 'v16', plate: '云F03990D', trailer: '云F990挂', driver: '罗仕华', owner: '华银物流队', projectId: 'p3', status: '运营中', model: '新能源重卡' },
  { id: 'v17', plate: '桂L58216D', trailer: '桂L216挂', driver: '覃伟', owner: '华银物流队', projectId: 'p3', status: '运营中', model: '燃油牵引车' },
  { id: 'v18', plate: '粤B41276D', trailer: '桂L276挂', driver: '黄开亮', owner: '华银物流队', projectId: 'p3', status: '待检修', model: '新能源重卡' },
  { id: 'v19', plate: '赣J05067D', trailer: '赣J067挂', driver: '张朴全', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v20', plate: '赣J09113D', trailer: '赣J913挂', driver: '赵云江', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v21', plate: '赣J05857D', trailer: '赣J857挂', driver: '高洪伟', owner: '云南云志合通', projectId: 'p1', status: '运营中', model: '新能源重卡' },
  { id: 'v22', plate: '赣J05805D', trailer: '赣J805挂', driver: '邱红志', owner: '云南云志合通', projectId: 'p1', status: '待检修', model: '新能源重卡' },
  { id: 'v23', plate: '沪A25320A', trailer: '沪A230挂', driver: '杜海', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '燃油牵引车' },
  { id: 'v24', plate: '沪A16328A', trailer: '沪A328挂', driver: '林国强', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '新能源重卡' },
  { id: 'v25', plate: '沪A17690A', trailer: '沪A690挂', driver: '宋小龙', owner: '曲靖捷运', projectId: 'p2', status: '运营中', model: '燃油牵引车' },
  { id: 'v26', plate: '沪A19865A', trailer: '沪A865挂', driver: '蒋卫', owner: '曲靖捷运', projectId: 'p2', status: '停运', model: '燃油牵引车' },
  { id: 'v27', plate: '桂L71908D', trailer: '桂L908挂', driver: '陆远', owner: '华银物流队', projectId: 'p3', status: '运营中', model: '新能源重卡' },
  { id: 'v28', plate: '粤B53619D', trailer: '桂L619挂', driver: '钟明', owner: '华银物流队', projectId: 'p3', status: '运营中', model: '新能源重卡' },
  { id: 'v29', plate: '桂L60935D', trailer: '桂L935挂', driver: '莫海亮', owner: '华银物流队', projectId: 'p3', status: '运营中', model: '燃油牵引车' },
  { id: 'v30', plate: '粤B75028D', trailer: '桂L028挂', driver: '梁军', owner: '华银物流队', projectId: 'p3', status: '停运', model: '新能源重卡' },
  { id: 'v31', plate: '云C60218D', trailer: '云C218挂', driver: '曹森', owner: '昭通顺联车队', projectId: 'p4', status: '运营中', model: '新能源重卡' },
  { id: 'v32', plate: '云C71329D', trailer: '云C329挂', driver: '李勇康', owner: '昭通顺联车队', projectId: 'p4', status: '运营中', model: '燃油牵引车' },
  { id: 'v33', plate: '云C80561D', trailer: '云C561挂', driver: '杨建波', owner: '昭通顺联车队', projectId: 'p4', status: '运营中', model: '新能源重卡' },
  { id: 'v34', plate: '川A29416D', trailer: '川A416挂', driver: '周洪', owner: '昭通顺联车队', projectId: 'p4', status: '待检修', model: '燃油牵引车' },
  { id: 'v35', plate: '贵A38172D', trailer: '贵A172挂', driver: '谭小平', owner: '昭通顺联车队', projectId: 'p4', status: '运营中', model: '新能源重卡' },
  { id: 'v36', plate: '云C46620D', trailer: '云C620挂', driver: '赵兴', owner: '昭通顺联车队', projectId: 'p4', status: '运营中', model: '燃油牵引车' },
  { id: 'v37', plate: '贵E11892D', trailer: '贵E892挂', driver: '黄俊杰', owner: '黔西南联运', projectId: 'p5', status: '运营中', model: '新能源重卡' },
  { id: 'v38', plate: '贵E35077D', trailer: '贵E077挂', driver: '韦光明', owner: '黔西南联运', projectId: 'p5', status: '运营中', model: '燃油牵引车' },
  { id: 'v39', plate: '云F72016D', trailer: '云F016挂', driver: '刘贵', owner: '黔西南联运', projectId: 'p5', status: '待检修', model: '燃油牵引车' },
  { id: 'v40', plate: '桂L83520D', trailer: '桂L520挂', driver: '梁启文', owner: '黔西南联运', projectId: 'p5', status: '运营中', model: '新能源重卡' },
  { id: 'v41', plate: '贵E50638D', trailer: '贵E638挂', driver: '陈东', owner: '黔西南联运', projectId: 'p5', status: '运营中', model: '新能源重卡' },
  { id: 'v42', plate: '贵E92901D', trailer: '贵E901挂', driver: '王志', owner: '黔西南联运', projectId: 'p5', status: '运营中', model: '燃油牵引车' },
  { id: 'v43', plate: '云A67318D', trailer: '云A318挂', driver: '沈立军', owner: '滇中新材料车队', projectId: 'p6', status: '运营中', model: '新能源重卡' },
  { id: 'v44', plate: '云A42065D', trailer: '云A065挂', driver: '顾涛', owner: '滇中新材料车队', projectId: 'p6', status: '运营中', model: '新能源重卡' },
  { id: 'v45', plate: '云D70619D', trailer: '云D619挂', driver: '方健', owner: '滇中新材料车队', projectId: 'p6', status: '运营中', model: '燃油牵引车' },
  { id: 'v46', plate: '云A85126D', trailer: '云A126挂', driver: '马卫国', owner: '滇中新材料车队', projectId: 'p6', status: '待检修', model: '新能源重卡' },
  { id: 'v47', plate: '云G90318D', trailer: '云G318挂', driver: '杜江', owner: '滇中新材料车队', projectId: 'p6', status: '运营中', model: '燃油牵引车' },
  { id: 'v48', plate: '云A50627D', trailer: '云A627挂', driver: '秦凯', owner: '滇中新材料车队', projectId: 'p6', status: '运营中', model: '新能源重卡' },
  { id: 'v49', plate: '桂L31670D', trailer: '桂L670挂', driver: '苏建华', owner: '百色矿业车队', projectId: 'p7', status: '运营中', model: '新能源重卡' },
  { id: 'v50', plate: '桂L48293D', trailer: '桂L293挂', driver: '农伟', owner: '百色矿业车队', projectId: 'p7', status: '运营中', model: '燃油牵引车' },
  { id: 'v51', plate: '粤B61827D', trailer: '桂L827挂', driver: '梁少杰', owner: '百色矿业车队', projectId: 'p7', status: '运营中', model: '新能源重卡' },
  { id: 'v52', plate: '桂A72051D', trailer: '桂A051挂', driver: '蓝海', owner: '百色矿业车队', projectId: 'p7', status: '待检修', model: '燃油牵引车' },
  { id: 'v53', plate: '桂L90516D', trailer: '桂L516挂', driver: '陆志强', owner: '百色矿业车队', projectId: 'p7', status: '运营中', model: '新能源重卡' },
  { id: 'v54', plate: '粤B44029D', trailer: '桂L029挂', driver: '莫健', owner: '百色矿业车队', projectId: 'p7', status: '运营中', model: '燃油牵引车' }
];

export const weighBills: WeighBill[] = [
  {
    id: 'WB20260629001',
    type: '出发磅单',
    projectId: 'p1',
    receiver: '广西德保电厂',
    shipper: '云南省煤炭交易（储配）中心有限公司',
    goods: '褐煤32',
    mineType: '32-2',
    gross: 63.46,
    tare: 18.76,
    net: 44.7,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J03528D',
    driver: '罗明',
    remark: '砚山-靖西',
    maker: '伍敏通',
    date: '2026-06-29',
    time: '10:38',
    source: '微信群/司机罗明',
    confidence: 0.93,
    auditStatus: '待审核',
    anomalies: ['等待到货单匹配'],
    freight: 2910,
    cost: 812,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260629002',
    type: '到货磅单',
    projectId: 'p1',
    receiver: '广西德保电厂',
    shipper: '云南省煤炭交易（储配）中心有限公司',
    goods: '褐煤32',
    mineType: '32-2',
    gross: 63.64,
    tare: 19,
    net: 44.64,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J03528D',
    driver: '罗明',
    remark: '靖西入库',
    maker: '伍敏通',
    date: '2026-06-29',
    time: '21:35',
    source: '微信群/司机罗明',
    confidence: 0.95,
    auditStatus: '待审核',
    anomalies: [],
    freight: 2874,
    cost: 816,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260628003',
    type: '出发磅单',
    projectId: 'p1',
    receiver: '广西华银铝业',
    shipper: '云南砚山矿务',
    goods: '散装氧化铝',
    mineType: 'A-17',
    gross: 61.72,
    tare: 18.83,
    net: 42.89,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J01379D',
    driver: '邓华',
    remark: '华银-砚山',
    maker: '杨丹',
    date: '2026-06-28',
    time: '09:26',
    source: '微信群/司机邓华',
    confidence: 0.91,
    auditStatus: '已通过',
    anomalies: [],
    freight: 2788,
    cost: 624,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260628004',
    type: '到货磅单',
    projectId: 'p1',
    receiver: '广西华银铝业',
    shipper: '云南砚山矿务',
    goods: '散装氧化铝',
    mineType: 'A-17',
    gross: 61.61,
    tare: 18.78,
    net: 42.83,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J01379D',
    driver: '邓华',
    remark: '砚山到货',
    maker: '杨丹',
    date: '2026-06-28',
    time: '17:42',
    source: '微信群/司机邓华',
    confidence: 0.94,
    auditStatus: '已通过',
    anomalies: [],
    freight: 2784,
    cost: 618,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260627005',
    type: '出发磅单',
    projectId: 'p1',
    receiver: '广西德保电厂',
    shipper: '云南煤炭交易中心',
    goods: '褐煤32',
    mineType: '32-2',
    gross: 64.12,
    tare: 19.05,
    net: 45.07,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J00236D',
    driver: '刘启',
    remark: '靖西线',
    maker: '伍敏通',
    date: '2026-06-27',
    time: '08:58',
    source: '微信群/司机刘启',
    confidence: 0.89,
    auditStatus: '有疑点',
    anomalies: ['缺少到货单'],
    freight: 2930,
    cost: 1050,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260627006',
    type: '到货磅单',
    projectId: 'p1',
    receiver: '广西德保电厂',
    shipper: '云南煤炭交易中心',
    goods: '褐煤32',
    mineType: '32-2',
    gross: 63.92,
    tare: 19.13,
    net: 44.79,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J05550D',
    driver: '张勇',
    remark: '疑似车牌误识别',
    maker: '伍敏通',
    date: '2026-06-27',
    time: '18:33',
    source: '微信群/司机刘启',
    confidence: 0.82,
    auditStatus: '有疑点',
    anomalies: ['车牌不一致', '可能匹配赣J00236D'],
    freight: 2911,
    cost: 1112,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260626007',
    type: '出发磅单',
    projectId: 'p1',
    receiver: '广西华银铝业',
    shipper: '云南砚山矿务',
    goods: '氧化铝',
    mineType: 'A-20',
    gross: 62.88,
    tare: 18.91,
    net: 43.97,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J05550D',
    driver: '张勇',
    remark: '华银入库',
    maker: '杨丹',
    date: '2026-06-26',
    time: '11:22',
    source: '微信群/司机张勇',
    confidence: 0.9,
    auditStatus: '已通过',
    anomalies: [],
    freight: 2858,
    cost: 920,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260626008',
    type: '到货磅单',
    projectId: 'p1',
    receiver: '广西华银铝业',
    shipper: '云南砚山矿务',
    goods: '氧化铝',
    mineType: 'A-20',
    gross: 62.42,
    tare: 18.94,
    net: 43.48,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J05550D',
    driver: '张勇',
    remark: '磅差偏大',
    maker: '杨丹',
    date: '2026-06-26',
    time: '19:10',
    source: '微信群/司机张勇',
    confidence: 0.88,
    auditStatus: '有疑点',
    anomalies: ['重量不一致'],
    freight: 2826,
    cost: 1188,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260625009',
    type: '出发磅单',
    projectId: 'p2',
    receiver: '曲靖园区料场',
    shipper: '富源采石场',
    goods: '砂石料',
    mineType: 'S-02',
    gross: 58.3,
    tare: 18.1,
    net: 40.2,
    carrier: '曲靖捷运物流',
    vehiclePlate: '沪A20170A',
    driver: '王成',
    remark: '园区短倒',
    maker: '陈会计',
    date: '2026-06-25',
    time: '07:40',
    source: '微信群/司机王成',
    confidence: 0.92,
    auditStatus: '已通过',
    anomalies: [],
    freight: 1608,
    cost: 602,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260625010',
    type: '到货磅单',
    projectId: 'p2',
    receiver: '曲靖园区料场',
    shipper: '富源采石场',
    goods: '砂石料',
    mineType: 'S-02',
    gross: 58.22,
    tare: 18.08,
    net: 40.14,
    carrier: '曲靖捷运物流',
    vehiclePlate: '沪A20170A',
    driver: '王成',
    remark: '园区短倒',
    maker: '陈会计',
    date: '2026-06-25',
    time: '11:21',
    source: '微信群/司机王成',
    confidence: 0.94,
    auditStatus: '已通过',
    anomalies: [],
    freight: 1605,
    cost: 580,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260625011',
    type: '出发磅单',
    projectId: 'p2',
    receiver: '宣威搅拌站',
    shipper: '曲靖料场',
    goods: '机制砂',
    mineType: 'M-11',
    gross: 57.95,
    tare: 18.41,
    net: 39.54,
    carrier: '曲靖捷运物流',
    vehiclePlate: '沪A16565A',
    driver: '陈力',
    remark: '宣威二线',
    maker: '陈会计',
    date: '2026-06-25',
    time: '13:10',
    source: '微信群/司机陈力',
    confidence: 0.87,
    auditStatus: '待审核',
    anomalies: ['识别置信度偏低'],
    freight: 1779,
    cost: 662,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260625012',
    type: '到货磅单',
    projectId: 'p2',
    receiver: '宣威搅拌站',
    shipper: '曲靖料场',
    goods: '机制砂',
    mineType: 'M-11',
    gross: 57.9,
    tare: 18.39,
    net: 39.51,
    carrier: '曲靖捷运物流',
    vehiclePlate: '沪A16565A',
    driver: '陈力',
    remark: '宣威二线',
    maker: '陈会计',
    date: '2026-06-25',
    time: '17:32',
    source: '微信群/司机陈力',
    confidence: 0.91,
    auditStatus: '待审核',
    anomalies: [],
    freight: 1778,
    cost: 648,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260624013',
    type: '出发磅单',
    projectId: 'p3',
    receiver: '田东华银料场',
    shipper: '广西华银铝业',
    goods: '氧化铝',
    mineType: 'H-06',
    gross: 61.32,
    tare: 18.55,
    net: 42.77,
    carrier: '华银物流队',
    vehiclePlate: '粤B98790D',
    driver: '何明军',
    remark: '华银-田东',
    maker: '覃会计',
    date: '2026-06-24',
    time: '08:19',
    source: '微信群/司机何明军',
    confidence: 0.93,
    auditStatus: '已通过',
    anomalies: [],
    freight: 2566,
    cost: 2102,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260624014',
    type: '到货磅单',
    projectId: 'p3',
    receiver: '田东华银料场',
    shipper: '广西华银铝业',
    goods: '氧化铝',
    mineType: 'H-06',
    gross: 61.2,
    tare: 18.51,
    net: 42.69,
    carrier: '华银物流队',
    vehiclePlate: '粤B98790D',
    driver: '何明军',
    remark: '田东入库',
    maker: '覃会计',
    date: '2026-06-24',
    time: '16:02',
    source: '微信群/司机何明军',
    confidence: 0.93,
    auditStatus: '已通过',
    anomalies: [],
    freight: 2561,
    cost: 2033,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260623015',
    type: '出发磅单',
    projectId: 'p3',
    receiver: '靖西中转库',
    shipper: '田东华银料场',
    goods: '氧化铝',
    mineType: 'H-08',
    gross: 60.92,
    tare: 18.62,
    net: 42.3,
    carrier: '华银物流队',
    vehiclePlate: '沪A15230A',
    driver: '李进',
    remark: '负利润案例',
    maker: '覃会计',
    date: '2026-06-23',
    time: '07:55',
    source: '微信群/司机李进',
    confidence: 0.86,
    auditStatus: '有疑点',
    anomalies: ['单车利润为负', '缺少到货单'],
    freight: 2199,
    cost: 2760,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260622016',
    type: '出发磅单',
    projectId: 'p2',
    receiver: '曲靖园区料场',
    shipper: '富源采石场',
    goods: '砂石料',
    mineType: 'S-02',
    gross: 59.22,
    tare: 18.2,
    net: 41.02,
    carrier: '曲靖捷运物流',
    vehiclePlate: '沪A20170A',
    driver: '王成',
    remark: '疑似重复提交',
    maker: '陈会计',
    date: '2026-06-22',
    time: '09:18',
    source: '微信群/司机王成',
    confidence: 0.9,
    auditStatus: '有疑点',
    anomalies: ['疑似重复单'],
    freight: 1641,
    cost: 591,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260622017',
    type: '出发磅单',
    projectId: 'p2',
    receiver: '曲靖园区料场',
    shipper: '富源采石场',
    goods: '砂石料',
    mineType: 'S-02',
    gross: 59.22,
    tare: 18.2,
    net: 41.02,
    carrier: '曲靖捷运物流',
    vehiclePlate: '沪A20170A',
    driver: '王成',
    remark: '重复图片二次发送',
    maker: '陈会计',
    date: '2026-06-22',
    time: '09:19',
    source: '微信群/司机王成',
    confidence: 0.9,
    auditStatus: '待审核',
    anomalies: ['疑似重复单'],
    freight: 1641,
    cost: 591,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260621018',
    type: '到货磅单',
    projectId: 'p1',
    receiver: '广西华银铝业',
    shipper: '云南砚山矿务',
    goods: '氧化铝',
    mineType: 'A-21',
    gross: 63.11,
    tare: 18.95,
    net: 44.16,
    carrier: '云志合通科技（云南）有限公司',
    vehiclePlate: '赣J01379D',
    driver: '邓华',
    remark: '补传到货单',
    maker: '杨丹',
    date: '2026-06-21',
    time: '20:02',
    source: '微信群/司机邓华',
    confidence: 0.96,
    auditStatus: '已通过',
    anomalies: [],
    freight: 2869,
    cost: 604,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260620019',
    type: '出发磅单',
    projectId: 'p3',
    receiver: '田东华银料场',
    shipper: '广西华银铝业',
    goods: '氧化铝',
    mineType: 'H-06',
    gross: 61.04,
    tare: 18.42,
    net: 42.62,
    carrier: '华银物流队',
    vehiclePlate: '粤B98790D',
    driver: '何明军',
    remark: '田东二趟',
    maker: '覃会计',
    date: '2026-06-20',
    time: '08:05',
    source: '微信群/司机何明军',
    confidence: 0.88,
    auditStatus: '待审核',
    anomalies: [],
    freight: 2557,
    cost: 1984,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  },
  {
    id: 'WB20260620020',
    type: '未识别',
    projectId: 'p3',
    receiver: '田东华银料场',
    shipper: '广西华银铝业',
    goods: '疑似氧化铝',
    mineType: '--',
    gross: 0,
    tare: 0,
    net: 0,
    carrier: '华银物流队',
    vehiclePlate: '粤B98790D',
    driver: '何明军',
    remark: '图片遮挡严重',
    maker: '未知',
    date: '2026-06-20',
    time: '18:22',
    source: '微信群/司机何明军',
    confidence: 0.54,
    auditStatus: '待审核',
    anomalies: ['识别置信度偏低', '关键重量缺失'],
    freight: 0,
    cost: 0,
    image: weighImage,
    fieldBoxes: weighFieldBoxes
  }
];

export const reimbursements: Expense[] = [
  {
    id: 'EX20260629001',
    projectId: 'p3',
    driver: '何明军',
    vehiclePlate: '粤B98790D',
    type: '补电费',
    item: '龙临补电',
    amount: 43,
    occurredDate: '2026-06-29',
    submittedAt: '2026-06-29 21:12',
    images: [expenseImages[0], expenseImages[6]],
    payee: '中石油广西百色靖西市龙临加油充电站',
    payStatus: '未付款',
    auditStatus: '待审核',
    anomalies: ['凭证金额43.08，提报43.00'],
    confidence: 0.91,
    message: '报销帐目：2026年6月27~29日，车牌粤B98790D，司机何明军，线路华银-砚山-田东-砚山，龙临补电43元。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260629002',
    projectId: 'p3',
    driver: '何明军',
    vehiclePlate: '粤B98790D',
    type: '加水费',
    item: '加水三次',
    amount: 15,
    occurredDate: '2026-06-28',
    submittedAt: '2026-06-29 21:12',
    images: [expenseImages[0], expenseImages[1]],
    payee: '锦江快递寄存点',
    payStatus: '未付款',
    auditStatus: '待审核',
    anomalies: [],
    confidence: 0.89,
    message: '司机提报：加水三次15元，附微信支付截图。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260629003',
    projectId: 'p3',
    driver: '何明军',
    vehiclePlate: '粤B98790D',
    type: '罚款',
    item: '交警罚款',
    amount: 30,
    occurredDate: '2026-06-27',
    submittedAt: '2026-06-29 21:12',
    images: [expenseImages[0]],
    payee: '交警现场缴费',
    payStatus: '未付款',
    auditStatus: '有疑点',
    anomalies: ['凭证缺失', '费用类型需老板确认'],
    confidence: 0.78,
    message: '司机提报：交警罚款30元，未附单独凭证。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260628004',
    projectId: 'p1',
    driver: '罗明',
    vehiclePlate: '赣J03528D',
    type: '过路费',
    item: '靖西高速通行费',
    amount: 168,
    occurredDate: '2026-06-28',
    submittedAt: '2026-06-28 20:16',
    images: [expenseImages[2]],
    payee: '广西高速收费站',
    payStatus: '未付款',
    auditStatus: '已通过',
    anomalies: [],
    confidence: 0.94,
    message: '靖西高速通行费168元，车号赣J03528D。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260628005',
    projectId: 'p1',
    driver: '罗明',
    vehiclePlate: '赣J03528D',
    type: '油费',
    item: '砚山服务区柴油',
    amount: 520,
    occurredDate: '2026-06-28',
    submittedAt: '2026-06-28 21:02',
    images: [expenseImages[3]],
    payee: '砚山服务区加油站',
    payStatus: '部分付款',
    auditStatus: '待审核',
    anomalies: ['金额不清晰'],
    confidence: 0.82,
    message: '砚山服务区柴油520元，票面有反光。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260627006',
    projectId: 'p1',
    driver: '刘启',
    vehiclePlate: '赣J00236D',
    type: '维修费',
    item: '补胎及气路检查',
    amount: 260,
    occurredDate: '2026-06-27',
    submittedAt: '2026-06-27 19:21',
    images: [expenseImages[4]],
    payee: '靖西轮胎维修店',
    payStatus: '未付款',
    auditStatus: '有疑点',
    anomalies: ['与行程不匹配'],
    confidence: 0.84,
    message: '车辆赣J00236D维修费260元，定位与当日运输路线不一致。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260627007',
    projectId: 'p1',
    driver: '刘启',
    vehiclePlate: '赣J00236D',
    type: '维修费',
    item: '补胎及气路检查',
    amount: 260,
    occurredDate: '2026-06-27',
    submittedAt: '2026-06-27 19:24',
    images: [expenseImages[4]],
    payee: '靖西轮胎维修店',
    payStatus: '未付款',
    auditStatus: '待审核',
    anomalies: ['重复报销'],
    confidence: 0.88,
    message: '同司机同金额同类型3分钟内重复提报。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260626008',
    projectId: 'p1',
    driver: '邓华',
    vehiclePlate: '赣J01379D',
    type: '停车费',
    item: '德保电厂排队停车',
    amount: 35,
    occurredDate: '2026-06-26',
    submittedAt: '2026-06-26 23:03',
    images: [expenseImages[5]],
    payee: '德保停车场',
    payStatus: '部分付款',
    auditStatus: '已通过',
    anomalies: [],
    confidence: 0.93,
    message: '德保电厂排队停车35元。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260626009',
    projectId: 'p2',
    driver: '王成',
    vehiclePlate: '沪A20170A',
    type: '油费',
    item: '富源油站柴油',
    amount: 480,
    occurredDate: '2026-06-25',
    submittedAt: '2026-06-26 08:42',
    images: [expenseImages[3]],
    payee: '富源中石化',
    payStatus: '已付款',
    auditStatus: '已通过',
    anomalies: [],
    confidence: 0.92,
    message: '富源中石化柴油480元，已付款。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260625010',
    projectId: 'p2',
    driver: '陈力',
    vehiclePlate: '沪A16565A',
    type: '过磅费',
    item: '宣威站过磅',
    amount: 20,
    occurredDate: '2026-06-25',
    submittedAt: '2026-06-25 18:42',
    images: [expenseImages[1]],
    payee: '宣威过磅点',
    payStatus: '未付款',
    auditStatus: '待审核',
    anomalies: [],
    confidence: 0.9,
    message: '宣威站过磅20元。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260624011',
    projectId: 'p3',
    driver: '李进',
    vehiclePlate: '沪A15230A',
    type: '维修费',
    item: '电控系统检查',
    amount: 1180,
    occurredDate: '2026-06-24',
    submittedAt: '2026-06-24 20:09',
    images: [expenseImages[4]],
    payee: '田东汽修厂',
    payStatus: '未付款',
    auditStatus: '有疑点',
    anomalies: ['超预算', '单车利润为负'],
    confidence: 0.86,
    message: '电控系统检查1180元，超出单车维修预算。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260624012',
    projectId: 'p3',
    driver: '何明军',
    vehiclePlate: '粤B98790D',
    type: '餐费',
    item: '田东等待卸货餐费',
    amount: 48,
    occurredDate: '2026-06-24',
    submittedAt: '2026-06-24 22:10',
    images: [expenseImages[5]],
    payee: '田东快餐店',
    payStatus: '已付款',
    auditStatus: '已通过',
    anomalies: [],
    confidence: 0.93,
    message: '等待卸货餐费48元。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260623013',
    projectId: 'p1',
    driver: '张勇',
    vehiclePlate: '赣J05550D',
    type: '住宿费',
    item: '靖西临停住宿',
    amount: 120,
    occurredDate: '2026-06-23',
    submittedAt: '2026-06-23 23:41',
    images: [expenseImages[2]],
    payee: '靖西商务宾馆',
    payStatus: '未付款',
    auditStatus: '待审核',
    anomalies: ['与行程不匹配'],
    confidence: 0.8,
    message: '靖西临停住宿120元，系统未匹配到该车当日到货排队。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260622014',
    projectId: 'p2',
    driver: '王成',
    vehiclePlate: '沪A20170A',
    type: '停车费',
    item: '园区临停',
    amount: 18,
    occurredDate: '2026-06-22',
    submittedAt: '2026-06-22 16:31',
    images: [expenseImages[1]],
    payee: '园区停车点',
    payStatus: '已付款',
    auditStatus: '已通过',
    anomalies: [],
    confidence: 0.95,
    message: '园区临停18元。',
    fieldBoxes: expenseFieldBoxes
  },
  {
    id: 'EX20260621015',
    projectId: 'p1',
    driver: '罗明',
    vehiclePlate: '赣J03528D',
    type: '其他费用',
    item: '装货排队饮用水',
    amount: 24,
    occurredDate: '2026-06-21',
    submittedAt: '2026-06-21 13:18',
    images: [expenseImages[0]],
    payee: '砚山小卖部',
    payStatus: '未付款',
    auditStatus: '待审核',
    anomalies: ['凭证金额不清晰'],
    confidence: 0.76,
    message: '装货排队饮用水24元，截图中金额被遮挡。',
    fieldBoxes: expenseFieldBoxes
  }
];

export const quickPrompts = [
  '查看今日待审核磅单',
  '汇总本月每辆车利润',
  '检查赣J03528是否有缺失磅单',
  '查看司机罗明本月报销'
];

export const initialAgentMessages: AgentMessage[] = [
  {
    role: 'agent',
    content: '我已接入微信群磅单、报销凭证和历史 Excel 汇总表。可以直接问我待审核、利润、异常、车辆明细或导出汇总。',
    skills: ['图片识别', '账务校验', '利润归因'],
    resultCards: [
      { label: '待审核磅单', value: '8 单', tone: 'orange', action: 'weighAudit' },
      { label: '待审核报销', value: '7 笔', tone: 'orange', action: 'expenseAudit' },
      { label: '异常提醒', value: '13 条', tone: 'red' }
    ]
  }
];
